# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nuget Package

on:
  push:
    branches: [ "master" ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Add GitHub Packages NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/PetrichorWorkspace/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
